spring.application.name=task-management-api
spring.datasource.url=jdbc:postgresql://localhost:5432/taskmgmt
spring.datasource.username=admin
spring.datasource.password=passwd
spring.jpa.hibernate.ddl-auto=update